# Generated by Django 5.1.4 on 2024-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_humancard_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='humancard',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='humancard',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
